### ISSUE TITLE
Publish latest on pub.dev

### ISSUE THREAD

**Issue by Blimster** [knopp/msgpack_dart#11]
I want to use this package on the web platform. This is not possible because the latest version on https://pub.dev still have a dependency to `dart:io`. As the dependency is already removed on branch `master`, publish a new version to https://pub.dev, please.

**Comment by Blimster** [comment]
As a workaround, I forked this repository and release the package under [msgpack_dart_with_web](https://pub.dev/packages/msgpack_dart_with_web/versions/1.0.1).

**Comment by knopp** [comment]
Published 1.0.1.

**Comment by Blimster** [comment]
Great news, thanks! I will discontinue my workaround package on pub.dev.
