### ISSUE TITLE
version tags

### ISSUE THREAD

**Issue by zoechi** [knopp/msgpack_dart#4]
Thanks for providing this package.

Because the versions tab on pub.dev does not work,
I next checked the tags in the GitHub repo, but they are not maintained.
It's usually a good idea to apply a tag with each release to pub.dev.

https://dev.to/neshaz/a-tutorial-for-tagging-releases-in-git-147e

**Comment by knopp** [comment]
Thanks for the heads-up. I'll try to remember to make a tag for next release. Btw. pub.dev versions tab works quite well for me, what doesn't work for you?

**Comment by zoechi** [comment]
Great. Versions tab seems to be an issus with my machine. We're investigating.
